#:schema node_modules/wrangler/config-schema.json
name = "zhuanhuan96-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e4d54ae98d084c5a9519e2b900cafb23" }
]

[assets]
directory = "./public"
